window.PLANT_DOCTOR_API_URL = window.PLANT_DOCTOR_API_URL || "";
window.PLANT_DOCTOR_APP_TOKEN = window.PLANT_DOCTOR_APP_TOKEN || "";
window.PLANT_DOCTOR_AUTH_REQUIRED = window.PLANT_DOCTOR_AUTH_REQUIRED || false;
